import { Product } from "@/lib/types";

export const products: Product[] = [
  {
    id: 1,
    slug: "terracotta-vase",
    name: "Terracotta Vase",
    shortDescription: "Hand-thrown clay vase with matte finish.",
    description:
      "A hand-thrown terracotta vase designed for dried stems and fresh arrangements. Its warm color and natural imperfections make each piece unique.",
    price: 45,
    category: "Decor",
    material: "Terracotta Clay",
    origin: "Quetzaltenango, Guatemala",
    rating: 4.8,
    stock: 18,
    featured: true,
    colorToken: "#d5a17c",
  },
  {
    id: 2,
    slug: "linen-throw-blanket",
    name: "Linen Throw Blanket",
    shortDescription: "Soft woven throw for modern living spaces.",
    description:
      "A breathable linen throw blanket with subtle texture. Great for sofas, reading corners, or layering at the end of your bed.",
    price: 85,
    category: "Textiles",
    material: "European Linen",
    origin: "Antigua, Guatemala",
    rating: 4.9,
    stock: 12,
    featured: true,
    colorToken: "#cec5ae",
  },
  {
    id: 3,
    slug: "hand-carved-bowl",
    name: "Hand-Carved Bowl",
    shortDescription: "Solid wood serving bowl carved by artisans.",
    description:
      "A medium-size serving bowl carved from sustainably sourced wood. Perfect for fruit, salads, or as a centerpiece item.",
    price: 62,
    category: "Kitchen",
    material: "Sustainably Sourced Laurel Wood",
    origin: "Suchitepequez, Guatemala",
    rating: 4.7,
    stock: 10,
    featured: true,
    colorToken: "#b88958",
  },
  {
    id: 4,
    slug: "sage-ceramic-mug",
    name: "Sage Ceramic Mug",
    shortDescription: "Wheel-thrown mug with calming glaze.",
    description:
      "A ceramic mug with a satin sage glaze and comfortable grip. Designed for daily coffee and tea rituals.",
    price: 24,
    category: "Kitchen",
    material: "Stoneware Ceramic",
    origin: "San Juan Comalapa, Guatemala",
    rating: 4.6,
    stock: 40,
    featured: true,
    colorToken: "#b7c2a0",
  },
  {
    id: 5,
    slug: "woven-table-runner",
    name: "Woven Table Runner",
    shortDescription: "Textured cotton runner for handcrafted tablescapes.",
    description:
      "A woven cotton table runner made on a traditional loom. Adds natural texture and warmth to dining setups.",
    price: 39,
    category: "Textiles",
    material: "Organic Cotton",
    origin: "Totonicapan, Guatemala",
    rating: 4.5,
    stock: 20,
    colorToken: "#dfc3a8",
  },
  {
    id: 6,
    slug: "cedar-soy-candle",
    name: "Cedar Soy Candle",
    shortDescription: "Small-batch soy candle with cedar notes.",
    description:
      "A clean-burning soy candle with cedar and amber notes in a reusable ceramic vessel. Hand poured in small batches.",
    price: 28,
    category: "Wellness",
    material: "Soy Wax",
    origin: "Guatemala City, Guatemala",
    rating: 4.7,
    stock: 28,
    colorToken: "#c9b29d",
  },
  {
    id: 7,
    slug: "woven-wall-hanging",
    name: "Woven Wall Hanging",
    shortDescription: "Fiber art for neutral and modern interiors.",
    description:
      "A handwoven wall hanging made with natural fibers and soft earthy hues. Includes loop for easy installation.",
    price: 74,
    category: "Decor",
    material: "Cotton and Wool Blend",
    origin: "Solola, Guatemala",
    rating: 4.8,
    stock: 9,
    colorToken: "#c7b09c",
  },
  {
    id: 8,
    slug: "olive-wood-spoon-set",
    name: "Olive Wood Spoon Set",
    shortDescription: "Carved spoon pair for daily cooking.",
    description:
      "A set of two olive wood cooking spoons with smooth finish. Durable, heat resistant, and crafted for daily use.",
    price: 31,
    category: "Kitchen",
    material: "Olive Wood",
    origin: "Escuintla, Guatemala",
    rating: 4.4,
    stock: 22,
    colorToken: "#b6936d",
  },
  {
    id: 9,
    slug: "handloom-pillow-cover",
    name: "Handloom Pillow Cover",
    shortDescription: "Textured cover with hidden zip closure.",
    description:
      "A handloom pillow cover that blends contemporary geometry with traditional weaving techniques.",
    price: 42,
    category: "Textiles",
    material: "Cotton and Linen",
    origin: "Chimaltenango, Guatemala",
    rating: 4.6,
    stock: 16,
    colorToken: "#c8b6a0",
  },
  {
    id: 10,
    slug: "stone-incense-holder",
    name: "Stone Incense Holder",
    shortDescription: "Minimal carved holder for incense sticks.",
    description:
      "A carved stone incense holder with smooth edge details. Built for steady burning and easy cleanup.",
    price: 19,
    category: "Wellness",
    material: "Volcanic Stone",
    origin: "Sacatepequez, Guatemala",
    rating: 4.3,
    stock: 30,
    colorToken: "#9a958d",
  },
  {
    id: 11,
    slug: "artisan-tea-canister",
    name: "Artisan Tea Canister",
    shortDescription: "Ceramic storage canister with cork top.",
    description:
      "A handcrafted ceramic canister that keeps tea fresh while adding a warm visual accent to kitchen shelves.",
    price: 34,
    category: "Kitchen",
    material: "Glazed Ceramic and Cork",
    origin: "Jalapa, Guatemala",
    rating: 4.5,
    stock: 17,
    colorToken: "#b6a895",
  },
  {
    id: 12,
    slug: "calming-bath-salts",
    name: "Calming Bath Salts",
    shortDescription: "Mineral-rich soak with botanical oils.",
    description:
      "A relaxing blend of sea salts and botanical oils to support recovery and stress relief after long days.",
    price: 22,
    category: "Wellness",
    material: "Sea Salt and Essential Oils",
    origin: "Lake Atitlan, Guatemala",
    rating: 4.7,
    stock: 26,
    colorToken: "#d4c8be",
  },
];

export const featuredProducts = products.filter((product) => product.featured);

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((product) => product.slug === slug);
}
